on:
  - push

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: cloudy-apps/random-color-tap
      baseImage: cloud-cli/node:latest
      defaultBranch: main
      type: node
